### ISSUE TITLE
Link to keyboards

### ISSUE THREAD

**Issue by louckousse** [jhelvy/splitKbCompare#1]
This tool can lead to discover new keyboards. It'll be great to be able to go to the description of a keyboard directly from the interface.

I can do it if you're interested.

**Comment by jhelvy** [comment]
I've put links to the keyboards in the README, but putting them in the app itself might be a good idea if we can do it in a clean way. Right now clicking on the name selects it in the image overlay, which I think is pretty intuitive, and I'd like to keep it that way. 

One simple change could be to replace the GitHub logo to a word or phrase like "learn more" so they link to the README file.

**Comment by louckousse** [comment]
Maybe a little icon like on wikipedia for external link, just after the name of the board? That can be pretty clean and pretty usual for user.
What do you think?

**Comment by jhelvy** [comment]
That's maybe possible. The labels for each check box are set by the `label` argument in each `prettyCheckbox`. I define the label content in the `keyboards` data frame inside the config.R file. You would have to create another column that has the html code to create the external link and them put that into the `label` somehow.

**Comment by jhelvy** [comment]
I've made a lot of changes to the UI of the app. To try and incorporate this suggestion, I added an "About" page which has a list of supported keyboards with links to each.
