### ISSUE TITLE
Add Reviung39

### ISSUE THREAD

**Issue by russtoku** [jhelvy/splitKbCompare#10]
Would you add the Reviung39 keyboard from https://github.com/gtips/reviung/tree/master/reviung39?

Unfortunately, the switch plate is made from PCB material so there isn't a vector graphic of it.

**Comment by jhelvy** [comment]
Woah, nice little board! I'd love to add it, but I have to have a vector graphic to make it work. There has to be one somewhere no? Or can someone create one from an image?

**Comment by russtoku** [comment]
Yeah, sorry. Don't know of anyone who can generate an image from the PCB layout files.
If I ever go down that road, I'll be sure to provide an image.

**Comment by jhelvy** [comment]
Just looked closer at the repo and inside the acrylic-plate.zip folder there is a plate layout svg! So I'll add this eventually.

**Comment by jhelvy** [comment]
It's now added!
