### ISSUE TITLE
Add Mitosis

### ISSUE THREAD

**Issue by marfrit** [jhelvy/splitKbCompare#11]
kicad should be available here:

https://github.com/joric/mitosis-hardware/tree/joric_kicad

**Comment by jhelvy** [comment]
Hey, could you help me find an svg / vector graphic of the plate? I don't need the kicad, just the plate image.

**Comment by marfrit** [comment]
Does https://dynamic.reauktion.de/nextcloud/index.php/s/x3DAFXJq8LFWazC work? I'm new to this ;)

**Comment by jhelvy** [comment]
Thanks, that works! I just added it :)
