### ISSUE TITLE
A4 paper options

### ISSUE THREAD

**Issue by AlexDaniel** [jhelvy/splitKbCompare#12]
When saving as a PDF file to print it later, there's no option to use A4 paper (which is what the majority of Europe is using).

I think one can workaround the limitation with pdfjam:

```
pdfjam --suffix converted --scale 1.0 --landscape --paper a4paper splitKbComparison1.pdf
```

But I'm not sure if it is scaled correctly after the conversion. I had to adjust the scale parameter slightly (to 1.02) to get approximately the right scale. I don't know if it's an issue with my printer or just the consequence of conversion.

**Comment by jhelvy** [comment]
Thanks for pointing this out - I didn't realize A4 was the standard in Europe. 

This was pretty easy to incorporate. The app uses LaTeX to compile the PDF, so I just added a separate button now to print to either size. 

Could you try testing this see if it comes out to the correct scale?

**Comment by AlexDaniel** [comment]
Tested, works! Thank you!
