### ISSUE TITLE
Please consider adding dactyl manuform 5x6.

### ISSUE THREAD

**Issue by NabiYang** [jhelvy/splitKbCompare#14]

**Comment by jhelvy** [comment]
Hmm, I'm not sure how to do this. This app compares 2d plates, but the plate for a dactyl manuform is convex. Is there a vector graphic of the plate file?

**Comment by NabiYang** [comment]
oh i dunno about that. are those the cad files here? https://github.com/abstracthat/dactyl-manuform/tree/master/things it shows a 3d image when i click on one. makes sense that it's different because it's curved. i just hoped maybe you could do a 2d projection of it

**Comment by jhelvy** [comment]
Yeah these are all 3D cad files, but I don't know how to create a 2D projection of a 3D surface. It's not an apples-to-apples comparison, so I don't think this is going to work. I'll leave the issue open for now in case someone can figure out a reasonable solution.

**Comment by jhelvy** [comment]
Closing this since I don't think this will work given the 2D nature of this app.
