### ISSUE TITLE
More split staggered designs?

### ISSUE THREAD

**Issue by alanhoyle** [jhelvy/splitKbCompare#15]
I don't have vector graphics for any of these, but it would be nice to have the following split-staggered keyboards included:

Ultimate Hacking  KeyBoard:  https://ultimatehackingkeyboard.com/
Matias Ergo Pro: https://matias.ca/ergopro/pc/
Kinesis Freestyle Edge:  https://gaming.kinesis-ergo.com/edge/
Quefrency: https://keeb.io/products/quefrency-60-65-split-staggered-keyboard
Sinc:   https://keeb.io/collections/split-keyboard-parts/products/sinc-split-staggered-75-keyboard

Thanks for the great tool!

**Comment by jhelvy** [comment]
Just pulled the files for the Quefrency and Sinc, so I'll add those. If you can find some vector graphics for the other 3 boards I'll add them too. It's harder with the commercial boards since most of their designs are not open source.

**Comment by jhelvy** [comment]
Quefrency and Sinc are now added, UHK is up next. Still no luck with Matias. They have jpg images but no vector graphics.

**Comment by alanhoyle** [comment]
Awesome, thanks!


--
  -  Alan Hoyle  -  alan@alanhoyle.com  -  http://www.alanhoyle.com/  -

**Comment by jhelvy** [comment]
Everything on this list that I could find is up, so I'm going to close this.
