### ISSUE TITLE
Hey there, could we add the Ferris to your comparison app?

### ISSUE THREAD

**Issue by pierrechevalier83** [jhelvy/splitKbCompare#16]
The Ferris is a 34 keys split keyboard I designed, with a layout similar to the Kyria's; but much tinier with a lot less keys. It is open-source and all the kicad files are available here: https://github.com/pierrechevalier83/ferris/.

Would it be possible to add it to your app so people can easily do side-by-side comparisons with other keyboards?

I uploaded an svg file with the edge cuts and the switches positions [here](https://github.com/pierrechevalier83/ferris/blob/master/ferris-switches.svg) hoping it makes it a bit easier :smile:

**Comment by jhelvy** [comment]
It's now in the queue!

**Comment by pierrechevalier83** [comment]
Thank you 😀

**Comment by jhelvy** [comment]
Ferris is now up! Cool little board. Very similar to the Squiggle, which has 2u thumbs. Also check out the Arch36.

**Comment by pierrechevalier83** [comment]
Yay! Thank you 😀
