### ISSUE TITLE
Print left/mirror keyboard

### ISSUE THREAD

**Issue by bazd** [jhelvy/splitKbCompare#17]
Thanks a bunch for this tool - it's super handy!

Could a feature be added to allow printing of the left or mirror image of the right side of keyboard?

I haven't been able to find a working pdf mirror tool otherwise would just use that

Cheers

**Comment by jhelvy** [comment]
I'll add this to my todo list. As a quick fix, I could just add a button to print the mirror image, although it would only work for symmetric boards (some aren't), and the label names would be flipped. I'll try and implement that first, and if I have time I'll see if I can't actually fully support the actually left hand side.

**Comment by bazd** [comment]
Thanks @jhelvy :-)
