### ISSUE TITLE
Add Moonlander

### ISSUE THREAD

**Issue by currentlyuntitledz** [jhelvy/splitKbCompare#22]
Hey, could you add Moonlander into the comparison site?
![ZSA Moonlander](https://www.zsa.io/moonlander/)
Unfortunately I couldn't find an SVG of the layout but I found this .png from Oryx:
![Moonlander.png](https://user-images.githubusercontent.com/67495350/92321782-595c4500-f05f-11ea-886a-e66f9f344316.png)

**Comment by jhelvy** [comment]
I definitely need to add this. Let's keep searching - there's got to be a svg somewhere. I might also reach out to ZSA directly.

**Comment by MarioRicalde** [comment]
Hello! I got you some official files!

Inside the PDF that is senet by support for printing and a SVG I have cleaned up for you @jhelvy in case that works better.

[moonlander.zip](https://github.com/jhelvy/splitKbCompare/files/5416133/moonlander.zip)

Let me know if I can assist with anything else!

**Comment by jhelvy** [comment]
Awesome! Okay these will be added with the next batch :)

**Comment by jhelvy** [comment]
It's up!
