### ISSUE TITLE
Please add Darknight

### ISSUE THREAD

**Issue by macroxue** [jhelvy/splitKbCompare#23]
Please add my DIY keyboard at https://github.com/macroxue/keyboard-diy. Thanks!

Here is the SVG: https://github.com/macroxue/keyboard-diy/blob/master/models/darknight.svg

**Comment by jhelvy** [comment]
Wow, cool project! I'll add it to my queue.

**Comment by jhelvy** [comment]
Sorry this took so long but it's up now
