### ISSUE TITLE
Source for adding the Reviung 34 split

### ISSUE THREAD

**Issue by WallPhone** [jhelvy/splitKbCompare#26]
https://github.com/gtips/reviung/tree/master/reviung34split/gerber

**Comment by jhelvy** [comment]
Thanks - I'll add it during my next batch of boards to add!

**Comment by jhelvy** [comment]
Hmm...just looked through all the files and didn't see any vector graphic of the plate file, or at least not any in a form I can work with (e.g. .ai, .svg, .pdf, etc.). Is there any other source for files? I went to the build guide page but I can't read Japanese :)

**Comment by WallPhone** [comment]
I opened them in KiCad's gerber viewer and printed to file... it's quite
odd as the right half is mirrored and I couldn't figure out how to fip it.
But find attached something hopefully you can mirror back to normal!

**Comment by jhelvy** [comment]
I don't know what to do with KiCad files. I've got Adobe Illustrator so I can manipulate any vector graphic I get.

**Comment by WallPhone** [comment]
Feel free to reach out if you come across others! I'm learning this stuff
for fun, and nothing is better than real-world examples.

**Comment by jhelvy** [comment]
I've added the 41, couldn't find a file for the 34.
