### ISSUE TITLE
Add KeySeeBee

### ISSUE THREAD

**Issue by TeXitoi** [jhelvy/splitKbCompare#28]
Hi!

Can you add KeySeeBee: https://github.com/TeXitoi/keyseebee

Plate file in SVG for the right side, with origin on the center of the rest index switch: https://github.com/TeXitoi/keyseebee/blob/master/cad/plate_right.svg

Entry for keyboards.csv:
```csv
keyseebee,44,44,KeySeeBee,0,Aggressive,0,0,0,1,0,https://github.com/TeXitoi/keyseebee,NA
```

Tell me if you need more!

Thanks.

**Comment by jhelvy** [comment]
Sure! I've added it to my todo list. Got ~10 boards to add now...I'll get to them eventually!

**Comment by jhelvy** [comment]
It's up!

**Comment by TeXitoi** [comment]
Thanks, but the image is missplaced: The columns should be aligned with the corne, but here, it is shifted by one U.

**Comment by jhelvy** [comment]
Woops, my bad - fixed it! Thanks for the heads up!

**Comment by TeXitoi** [comment]
Great! Thanks!
