### ISSUE TITLE
Add Keyboardio Model 01

### ISSUE THREAD

**Issue by menelaos** [jhelvy/splitKbCompare#3]
It would be nice to see how [Keyboardio's Model 01](http://www.keyboard.io) compares to the other keyboards. Maybe @obra could help with the necessary files?

**Comment by jhelvy** [comment]
It's on my list to add! If I can get a vector graphic file of the layout it'd be pretty easy to add.

**Comment by jhelvy** [comment]
Okay, that wasn't too hard - just googled and found [this](https://github.com/keyboardio/Model01-Legends/tree/master/layout_card). I think I can get this up.

**Comment by jhelvy** [comment]
and done!

**Comment by menelaos** [comment]
Thanks a lot!
