### ISSUE TITLE
add a filter/column for row staggering

### ISSUE THREAD

**Issue by jasonlovesjazz** [jhelvy/splitKbCompare#31]
There are currently four keyboards on the list with row staggering and it would be great to filter by this very important data point.

Sinc
Quefrency R1
Quefrency R2
Dygma Raise

Thanks so much for this incredibly helpful tool.  I've been using a Kinesis Freestyle for several years.  I've been going down the keyboard rabbit hole for a couple weeks figuring out my next step.  Seeing direct scaled comparisons in your awesome tool helped me narrow way down to 2-4 choices (likely an Ergodash or Redox, although the simplicity of Nyquist is appealing).

I literally joined GitHub to make this suggestion.  (Been meaning to join for a while , of course.) 

Thanks again!

**Comment by jhelvy** [comment]
Great idea! Just added support for this. And welcome to github - glad to be the inspiration to join :)
