### ISSUE TITLE
filter by row count (with one criteria)

### ISSUE THREAD

**Issue by jasonlovesjazz** [jhelvy/splitKbCompare#32]
As I saw in another comment, ways to broadly filter the list would be helpful.  

I assume this was your goal in filtering with/without number row.  But with programmable and blank keys, it's a bit subjective since a 4x6 may or may not be intended or used with a numpad. 

A row count CAN avoid the complexity of thumb keys and corner key tweaks.  It also isn't impacted by row staggering and the many accompanying odd key widths.  In order to keep the number clean and non-subjective, the count could be based on the upper outside corner, except in by one column and down by one row.  It sounds finicky but it's fairly simple and avoids almost all issues.  

Currently there's only one that I would break the rule on.  I'd give Xenon a 3.5 for row count. You could use an asterisk for occasional oddities that may not quite fit the rule, or have an "other" category, or leave it blank (if you're okay with the dreaded null value).  

Otherwise, if you like it, I did the legwork already:

Name | BasicRowCount 
-- | --
Absolem | 3
Arch   36 | 3
Atreus | 4
Claw44 | 3
Corne | 3
DracuLad | 3
Dygma   Raise | 5
Elephant   42 | 3
Ergodash   1 | 5
Ergodash   2 | 5
Ergodox | 5
Ergoslab | 5
Ergotravel | 4
Ferris | 3
Georgi | 2
Gergo | 3
Gergoplex | 3
Ginny | 1
Interphase | 5
Iris | 4
Keyboardio   Model01 | 4
Keyseebee | 3
Kyria | 3
Lily58 | 4
Microdox | 3
Minidox | 3
Mitosis | 3
Moonlander | 5
Nyquist | 5
Quefrency   R1 | 5
Quefrency   R2 | 5
Redox | 5
Reviung   39 | 3
Reviung   41 | 3
Sinc | 6
Sofle | 4
Sol2 | 5
Squiggle | 3
Torn | 3
Viterbi | 5
Xenon | 3.5
Zen 2 | 5
Zygomorph | 5

Thanks again for this super cool tool!

**Comment by jhelvy** [comment]
Thanks for doing the work to identify these. I just added this filter too. I just made a call and said the xenon is a 3.
