### ISSUE TITLE
Add Sofle v2 (and rename Sofle to Sofle v1)?

### ISSUE THREAD

**Issue by Diamundo** [jhelvy/splitKbCompare#33]
Hi!

The main difference between the v2 and v1 is, as I understand:

- The middlefinger column is slightly moved up (increased stagger)
- The pinkey column and extra pinkey column (on the outside) are lowered, and they are now the same height.
- The thumb cluster has been moved to the middle/inside, and now the outside-most three thumbkeys are in the same columns as the main keys. 
  - Previously, the outside-most thumbkey was between the pinky and ringfinger column; in v2 it is entirely in the ringfinger column. 
  - This also means the board is a bit wider.

I think [this SVG file](https://github.com/josefadamcik/SofleKeyboard/blob/master/Design/v2/top_plate.svg) from the [official Sofle repository](https://github.com/josefadamcik/SofleKeyboard/) is what you need? Note that the encoder isn't 'marked' with an R in the SVG, that's still the same button as v1.

See also this image from [Josef Adamcik's blog](https://josefadamcik.github.io/SofleKeyboard/). _Note: I added the "v1", "v2" and red "R" in the image for clarity._

> Changes a stagger of columns and position of the bottom row a bit. The whole board was rerouted, shape changed slightly. Below version 1 in yellow, version 2 in blue.

![Comparison1_2](https://user-images.githubusercontent.com/8041052/106392121-bd0d5300-63f0-11eb-8037-b36cea4e22f3.png)

**Comment by jhelvy** [comment]
Done with [a1da8d1](https://github.com/jhelvy/splitKbCompare/commit/a1da8d126878b7905e823dc172e716781544ef2b)
