### ISSUE TITLE
Adding the Zodiark

### ISSUE THREAD

**Issue by Aleblazer** [jhelvy/splitKbCompare#34]
Hi! Designed a new split coming up for group buy soon, and was looking to possibly get it added to SplitKbCompare.

Source: https://github.com/Aleblazer/Zodiark-Case/blob/main/Zodiark%20Top%20Plate.svg
Note: Inner most thumb key is a rotary encoder
Store: https://www.splitlogic.xyz/
Keys: 68 (70 if you count the encoders)

Let me know if you have any questions!

**Comment by jhelvy** [comment]
Very cool! I'll add it to the list of boards to include in my next batch update.

**Comment by jhelvy** [comment]
This is up now!
