### ISSUE TITLE
Adding Corne-ish Zen

### ISSUE THREAD

**Issue by TLauzen** [jhelvy/splitKbCompare#35]
Could this kailh choc focused board be added?
https://www.thingiverse.com/thing:4698210

**Comment by LOWPROKB** [comment]
I can provide any files that are needed to add this board. Just let me know what you need

**Comment by LOWPROKB** [comment]
it is not... it is choc spaced

**Comment by jhelvy** [comment]
Ah, okay. Is there a vector graphic of the switch plate somewhere?

**Comment by LOWPROKB** [comment]
just making it for you

**Comment by LOWPROKB** [comment]
[Corne-ish_Zen_Plate.zip](https://github.com/jhelvy/splitKbCompare/files/6111182/Corne-ish_Zen_Plate.zip)

**Comment by jhelvy** [comment]
Is there a url to the source files for this board? Or a store?

**Comment by LOWPROKB** [comment]
it is not open source, but the case files will be.
https://lowprokb.ca/products/corne-ish-zen-2

The case files will be here within a week hopefully:
https://www.thingiverse.com/darryldh/designs

**Comment by jhelvy** [comment]
Got it. Okay, it's in my queue to add

**Comment by LOWPROKB** [comment]
Thanks John

**Comment by jhelvy** [comment]
It's up, but I had trouble getting it perfectly aligned. I think it's still a little off.

**Comment by LOWPROKB** [comment]
Hey thanks! Alignment is not too bad. 
Can you correct the spelling though? Its Corne-ish Zen with an "e" at the end of Corne
Thanks again

**Comment by jhelvy** [comment]
Fixed it!
