### ISSUE TITLE
Adding Balbuzard

### ISSUE THREAD

**Issue by brow** [jhelvy/splitKbCompare#38]
Here is another personal project of mine that I'd be interested to add if it's appropriate: https://github.com/brow/balbuzard

It's a plateless PCB-only design, but this might be a good "plate" SVG to use: https://gist.github.com/brow/e73ef7ac7cb8f7d8f7d1a0b0190f20c0

**Comment by jhelvy** [comment]
Wow this and the other one you posted is wild! I'll add them both to the queue!

**Comment by brow** [comment]
Great! And thanks for your work on this excellent tool, by the way :)

**Comment by jhelvy** [comment]
It's up!

**Comment by brow** [comment]
Woo, looks great! Some other very neat boards in this batch, too.
