### ISSUE TITLE
Add Claw44

### ISSUE THREAD

**Issue by notmgsk** [jhelvy/splitKbCompare#4]

**Comment by jhelvy** [comment]
Can you send a link to an svg or other vector image of the plate?

**Comment by notmgsk** [comment]
Does this work? I just grabbed it from https://github.com/yfuku/claw44/tree/master/case/top and converted it to SVG.

[top_plate.svg.zip](https://github.com/jhelvy/splitKbCompare/files/4340291/top_plate.svg.zip)

**Comment by jhelvy** [comment]
That'll do! Okay I'll try and add it later tonight.

**Comment by jhelvy** [comment]
...aaand that didn't happen last week, sorry. With everything going on, I have to table this for the time being. I'll add it eventually though - it's on the todo list.

**Comment by jhelvy** [comment]
Finally got this up! I had to make a bunch of other modifications to the app, and adding support for new layouts was the last step.

**Comment by notmgsk** [comment]
Awesome :D
