### ISSUE TITLE
Add YAEMK keyboard

### ISSUE THREAD

**Issue by KarlK90** [jhelvy/splitKbCompare#42]
Hi there :-),

I just finished my split keyboard [YAEMK](https://karlk90.github.io/yaemk-split-kb) if you could add it this would be great. Add switch plate can be found here: 

https://github.com/KarlK90/yaemk-split-kb/blob/main/Case/3mm%20acrylic/no%20kerf/YAEMK-top-2x1u-2x1u.svg

or this 

https://github.com/KarlK90/yaemk-split-kb/blob/main/Case/3mm%20acrylic/no%20kerf/YAEMK-top-template.svg

**Comment by jhelvy** [comment]
Looks great! I'll add it to the queue

**Comment by KarlK90** [comment]
Thank you :slightly_smiling_face:

**Comment by KarlK90** [comment]
Just uploaded the clean key layout today, this might work even better https://raw.githubusercontent.com/KarlK90/yaemk-split-kb/main/docs/images/yaemk_keylayout.svg

**Comment by jhelvy** [comment]
Awesome, I'll use this one

**Comment by jhelvy** [comment]
This is now up!

**Comment by KarlK90** [comment]
Thank you!
