### ISSUE TITLE
Add Splay46

### ISSUE THREAD

**Issue by mieumbat** [jhelvy/splitKbCompare#48]
Project: https://github.com/kobababa/Splay46

Switch plate here: https://github.com/kobababa/Splay46/blob/main/plate_dxf/plate_mx.dxf

Thank you!

**Comment by jhelvy** [comment]
Thanks, I'll try and add it next time I get a chance.

**Comment by jhelvy** [comment]
Okay this is now up with [52af4f2](https://github.com/jhelvy/splitKbCompare/commit/52af4f20ba4d06a7aa8fa241dd5f4a4fa9bd4891)
