### ISSUE TITLE
Add Fifi

### ISSUE THREAD

**Issue by soulsoiledit** [jhelvy/splitKbCompare#50]
Project: https://github.com/raychengy/fifi_split_keeb
Plates: https://github.com/raychengy/fifi_split_keeb/tree/main/plates

Thank you for the amazing comparison tool!

**Comment by jhelvy** [comment]
Thanks, I'll try and add it asap. Can you do me a favor and tell me the min and max number of keys for this board?

**Comment by jhelvy** [comment]
Thanks, I'll add it next chance I get.

**Comment by soulsoiledit** [comment]
I saw a comment asking about the minimum and maximum number of keys. The Fifi only supports 36 keys.

**Comment by jhelvy** [comment]
Thanks, I realized it right after I asked, so I just deleted my comment

**Comment by jhelvy** [comment]
Okay this is now up with [52af4f2](https://github.com/jhelvy/splitKbCompare/commit/52af4f20ba4d06a7aa8fa241dd5f4a4fa9bd4891)
