### ISSUE TITLE
please add 3w6

### ISSUE THREAD

**Issue by weteor** [jhelvy/splitKbCompare#51]
Keyboard name: 3w6
project source: https://github.com/weteor/3W6
switch plate: https://raw.githubusercontent.com/weteor/3W6/main/plate_outline.svg
Keys: 36

Thanks a lot!

**Comment by jhelvy** [comment]
Got it, I've added it to the queue for the next batch update

**Comment by jhelvy** [comment]
Okay this is now up with [52af4f2](https://github.com/jhelvy/splitKbCompare/commit/52af4f20ba4d06a7aa8fa241dd5f4a4fa9bd4891)
