### ISSUE TITLE
Add Pluckey

### ISSUE THREAD

**Issue by floookay** [jhelvy/splitKbCompare#52]
Hi, it'd be awesome if you could add my keyboard when you get the chance:

- [x] Keyboard name: pluckey
- [x] Url to vector graphic (e.g. svg, pdf, etc.) of switch plate: <https://github.com/floookay/pluckey/blob/main/case/plate/pluckey.svg>
- [x] Min and max number of keys: 64 - 68
- [x] Url to keyboard project source (if available): <https://github.com/floookay/pluckey>
- [x] Url to store to buy keyboard (if available): NA

I started working on opening a MR but saw in the meantime that you added an issue template. So here's my current effort:
```csv
pluckey,64,68,pluckey,1,1,0,5,Moderate,0,1,0,0,1,0,https://github.com/floookay/pluckey,NA
```
Unfortunately I wasn't able to open the overlay file correctly on my system.

Thanks!

**Comment by jhelvy** [comment]
Thanks! I'll add this in my next batch of new keyboards.

**Comment by jhelvy** [comment]
Okay this is now up with [52af4f2](https://github.com/jhelvy/splitKbCompare/commit/52af4f20ba4d06a7aa8fa241dd5f4a4fa9bd4891)

**Comment by floookay** [comment]
Awesome, thank you!
