### ISSUE TITLE
add filter kailh-choc vs cherry spacing

### ISSUE THREAD

**Issue by nicolasH** [jhelvy/splitKbCompare#55]
Hello, can you please add a filter to distinguish between kb that support cherry only, kailh choc only or both. it would be useful to find the compact keyboards.

Thank you for a wonderful app!

**Comment by jhelvy** [comment]
Happy to include this, but we'll need to update the [keyboards.csv](https://github.com/jhelvy/splitKbCompare/blob/master/keyboards.csv) file to note which keyboards support which switch type. I don't have the time to go through each one and figure this out, but if someone else can do that then I'll include the filter. I would suggest adding new columns `cherry` and `kailh_choc` with `0` or `1` to denote the switch type (note that if it supports both, each column would have a `1`).

**Comment by weteor** [comment]
I've updated the keyboards.csv with relevant information. see PR #56 for more.
