### ISSUE TITLE
Ferris layout is broken

### ISSUE THREAD

**Issue by duckyb** [jhelvy/splitKbCompare#57]
Reporting that the ferris keyboard is currently broken. The keys appear much bigger than they should.

![image](https://user-images.githubusercontent.com/27895007/128841211-0f1c38db-a3f7-4d3c-b0b3-e3479071a0bd.png)

Hope this can be fixed. Thanks!

**Comment by jhelvy** [comment]
It looks correct to me. Not all the boards have the same size "squares". It depends on the switch plate file that is available. For example, in this screenshot I've compared the Ferris, Kyria, and Gergo. The Gergo and Ferris have the same size squares but the Kyria's are smaller. But they're all still correctly aligned.

![Screen Shot 2021-08-10 at 5 56 19 AM](https://user-images.githubusercontent.com/9012994/128847429-884eb368-2faf-43fa-ad97-7dcd02b7f977.png)

**Comment by duckyb** [comment]
I see. It just seemed weird that the keys appeared so big, especially since they clip out of the frame in a couple of spots.
