### ISSUE TITLE
Install dependencies incomplete, and issue running still

### ISSUE THREAD

**Issue by bleys** [jhelvy/splitKbCompare#58]
I just tried running this on a fresh R install (because the site isn't loading). R is 4.1.1 from Arch pacman:
`version.string R version 4.1.1 (2021-08-10)`

I had to fix several additional dependencies with these commands:
```
install.packages("DT")
install.packages("dplyr")
install.packages("shinythemes")
install.packages("shinyWidgets")
install.packages("magick")
install.packages("readr")
install.packages("RColorBrewer")
install.packages("markdown")
```

After that it would run, but pretty quickly crashes without any window popping up. Here's the R terminal output:
```
> library(shiny)
runGitHub('jhelvy/splitKbCompare')
Downloading https://github.com/jhelvy/splitKbCompare/archive/master.tar.gz
Rows: 65 Columns: 22                                                                                               
── Column specification ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): id, name, colStagger, url_source, url_store
dbl (17): nKeysMin, nKeysMax, include, hasNumRow, hasFuncRow, numRows, rowSt...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Listening on http://127.0.0.1:7143
Error in utils::browseURL(appUrl) : 
  'browser' must be a non-empty character string
```

**Comment by bleys** [comment]
FWIW, I just duplicated this effort on a fresh R install from binary downloaded at [r-project.org in Win10](https://cloud.r-project.org/bin/windows/base/R-4.1.1-win.exe). It works there. The Downloading line pops up, and then it launches the interface in browser on port 3943 with no more terminal output.

**Comment by jhelvy** [comment]
Yeah this occasionally goes down on shinyapps.io, which is free. I'm never sure why sometimes, and I'm seeing what you mean - it never seems to load. Usually I just have to re-upload the whole app and it runs again. 

Good catch on the additional package dependencies. Yes, a user will need to install all of those to run it locally. I'll add that in a comment at the top of the app to run it locally, and I'll try and get to the root of why it's not loading online.

**Comment by bleys** [comment]
Thanks! Any idea why it's not running in Arch?

**Comment by jhelvy** [comment]
Not sure about Arch, but likely some package dependency issue. 

I just re-deployed the app and now it seems to be working on shinyapps.io again. 
Thanks for catching the dependency issue!
