### ISSUE TITLE
Provide URLs to keyboard shops / homepage

### ISSUE THREAD

**Issue by notmgsk** [jhelvy/splitKbCompare#7]

**Comment by jhelvy** [comment]
I have this on the "About" page on the app. I can't think of a better place to put it without it interfering with the UI for comparing the boards. Was there somewhere else you had in mind?

**Comment by notmgsk** [comment]
Ah, I didn't look at the about page since I assumed that was just going to tell me something about the app and its author. Maybe that's my mistake, and the information is perfectly fine there.

Otherwise, I think something like this could work:

<img width="1152" alt="Screen Shot 2020-04-10 at 12 18 21 PM" src="https://user-images.githubusercontent.com/16821631/79017155-809cfd80-7b25-11ea-8efd-6d8390760428.png">

A text element that looks like a link (underlined) and is short enough that it doesn't overflow / mess up the look of the page.

**Comment by jhelvy** [comment]
Given the limits of Shiny app UIs, I decided to just separate out the keyboards into a new tab. Hopefully that is more obvious than having it buried in the "About" page. Putting in a link in the actual comparison page I think will get rather clunky.

**Comment by jhelvy** [comment]
I have now gone one step further and made the table on the "Keyboards" page sort-able and also added more details about each keyboard. This provides a lot more information than could be shown in the UI of the comparison page.

**Comment by notmgsk** [comment]
Decent solution. 👍
