### ISSUE TITLE
moving your link in r/emk from a thread to a wiki entry

### ISSUE THREAD

**Issue by ibnuda** [jhelvy/splitKbCompare#70]
chief, i don't know how to contact you. and i am sorry if i clutter your issue page.

so, one of the users in r/emk in [a thread about sticky thread](https://www.reddit.com/r/ErgoMechKeyboards/comments/r68o5f/can_we_get_a_pinned_discussion_about_key_maps/) said that your useful utility fits as a wiki entry better than a thread. 
so, i want to inform you that i am going to unstick you thread for another thread that discusses about keymap.
hope it's ok for you.

cheers, rick.

**Comment by jhelvy** [comment]
Makes sense. Where would the wiki be? I didn't even know there was a Reddit wiki.

**Comment by ibnuda** [comment]
here's the link: https://old.reddit.com/r/ErgoMechKeyboards/wiki/index

**Comment by jhelvy** [comment]
got it

could you add a link to the wiki somewhere from the main https://www.reddit.com/r/ErgoMechKeyboards/

maybe at the top next to the links for the discords? 
![Screen Shot 2021-12-02 at 7 04 03 AM](https://user-images.githubusercontent.com/9012994/144418819-0274c6a6-daf5-48c5-a490-1442092db331.png)

**Comment by ibnuda** [comment]
Oh! I forgot that new reddit exists!
I also added the link to the top bar. 
![Screenshot_2021-12-03-16-00-04-95](https://user-images.githubusercontent.com/8169908/144574993-30cc0ffb-75d0-4aa4-a26c-d31884cd2eaf.png)

**Comment by jhelvy** [comment]
Oh cool, it's got it's own direct link! Well thanks for that, I'll go ahead and close this issue.
