### ISSUE TITLE
Search Engine Description

### ISSUE THREAD

**Issue by 73567876543783** [jhelvy/splitKbCompare#76]
Hi,

Whilst searching for the dashboard on google and duckduckgo I noticed that there is no description available. `index.html` seems to want to fix this but I guess it's just not included anywhere (?). Maybe putting it in a `www` directory would be a solution? I'm interested in hearing your experience with `index.html`.

**Google**
<img width="444" alt="Screenshot 2021-12-24 at 14 01 50" src="https://user-images.githubusercontent.com/74454337/147355102-fe41335d-ac65-4385-926d-b8255cb67c00.png">
**DuckDuckGo**
<img width="482" alt="Screenshot 2021-12-24 at 14 02 17" src="https://user-images.githubusercontent.com/74454337/147355104-75ed8dfa-6681-4ad3-af16-10d893e6359b.png">

And happy holidays of course :)

**Comment by jhelvy** [comment]
Good point. To my knowledge I haven't found a good solution to this. 

[Here's one idea](https://community.rstudio.com/t/how-can-i-make-shiny-app-appear-on-search-engine/41292/3?u=jhelvy)

Basically, we just put an index.html page in the repo that contains the app in an iframe. Then we use Github pages to host that page. 

The only issue is the url would change from https://jhelvy.shinyapps.io/splitkbcompare/ to https://jhelvy.github.io/splitkbcompare/

Not really that big of a change imo, but I'd have to get the link updated in Reddit too.

**Comment by 73567876543783** [comment]
So currently `index.html` has no use? Since it's already there we could setup Github pages without too much effort. But it's a bit neater to have only one link to the dashboard imo. I'd just leave it like this and maybe remove `index.html` from the repo.

**Comment by jhelvy** [comment]
Yeah I had apparently put `index.html` in there a long time ago to do exactly what I said - host the app on Github pages via an iframe. Looks like I turned pages off though, and I forgot why. I think it was just loading very slowly or something so I just abandoned it, but I left the `index.html` file there.

**Comment by jhelvy** [comment]
Just turned pages back on and now it looks like it's working just fine: https://jhelvy.github.io/splitKbCompare/

**Comment by 73567876543783** [comment]
I don't notice any difference in terms of speed. I'm not that up to date with github pages, but if there's some benefit in using it in combination with shinyapps.io that's nice!

**Comment by jhelvy** [comment]
Yes, I think one benefit is that it might show up in search engines, but also it gives me other flexibility in terms of hosting it elsewhere since all I need to do is point something to that `index.html` file.

For example, I just created a netlify site and pointed it to this repo. It found the `index.html` file and deployed it: https://splitkbcompare.netlify.app/

With a tiny bit more effort I think I might be able to make it a subdomain of my personal site, like https://splitkbcompare.jhelvy.com

**Comment by 73567876543783** [comment]
Good stuff! Seems like `index.html` is pretty useful after all :).
