### ISSUE TITLE
Add the Xenon keyboard

### ISSUE THREAD

**Issue by Kyrremann** [jhelvy/splitKbCompare#8]
Would it be possible to add the Xenon keyboard?
https://github.com/narinari/xenon-keyboard

SVG can be found here:
https://github.com/narinari/xenon-keyboard/blob/master/xenon-e/cad-data/xenon-e_plate.svg

There are several layers, as it support both regular switches and low-profile.
Mostly I want to see how close it is to Kyria.

**Comment by jhelvy** [comment]
Woah, cool board. Yeah I'll add that to my "add" list.

**Comment by jhelvy** [comment]
It's up! Pretty interesting board - it's basically a Kyria with a totally different thumb cluster.

**Comment by Kyrremann** [comment]
Thanks! It was a bigger difference then I thought, but still very similar.

I see that the version you added of the Xenon don't have the bottom row, where I have the choc switches.

**Comment by jhelvy** [comment]
Yeah the svg plate file didn't have them...I just went back and added them manually, so now they should be on the app.

**Comment by Kyrremann** [comment]
They are hidden in layers. Took some time for me to find them. The worst case file I've seen! Or, it's just too fancy for me.
