### ISSUE TITLE
Errors on hosted site with Chrome

### ISSUE THREAD

**Issue by thoni56** [jhelvy/splitKbCompare#82]
I get "Error: An error has occurred. Check your logs or contact the app author for clarification." on the live site for a fairly large number of keyboards. One of many examples is the Splay 46. Downloading the print view gives a correct drawing.

This seems to happen with Chrome (Chrome 98.0.4758.82 on Windows 10 Home 21H2 19044.1526) but not with Edge.

**Comment by jhelvy** [comment]
This is likely due to the limitations of the server. See similar issues #66 , #74 , #79

**Comment by thoni56** [comment]
Thanks for a *very* quick answer! Ok, closing.

**Comment by jhelvy** [comment]
If you [run the app locally](https://github.com/jhelvy/splitKbCompare#run-locally), you'll get very fast performance with usually far fewer crashes.
