### ISSUE TITLE
Kyria is not Open Source

### ISSUE THREAD

**Issue by hoijui** [jhelvy/splitKbCompare#86]
The kyria has a repo with an open source license, but that repo only contains files for cases, not for the PCB or anything else.
I wanted to change that with a PR, but I saw no OpenSource column in [keyboards.csv](https://github.com/jhelvy/splitKbCompare/blob/master/data/keyboards.csv).
How could I set it as non OS?

**Comment by jhelvy** [comment]
I don't keep track of whether a board is open source or not on this app. I just include links to the source (if available) and links to a store to buy it at (if available). I certainly appreciate open source boards, but I also understand if folks want to keep their design proprietary, especially if they sell it.

**Comment by hoijui** [comment]
well.. there is a filter named "OpenSource", so... is that ill-named then?

**Comment by hoijui** [comment]
![2022-06-09-20-59-05-area](https://user-images.githubusercontent.com/42907/172923797-455fc105-2f12-429c-8cfe-956975900754.png)

**Comment by jhelvy** [comment]
Huh...must have been added more recently. Others have contributed to the project more recently with a few suggested UI changes, that's one I didn't catch. I'll go find where it's pulling that from and will swap Kyria to the closed source list.

**Comment by jhelvy** [comment]
Okay I just updated the app. Someone had added the "open source" menu item based on whether there was a url for the "source". Kyria has a url to a github repo, but the repo doesn't include all the source files. So I just added a new `openSource` variable in the `keyboards.csv` file.
