### ISSUE TITLE
Add link to mechdb.net

### ISSUE THREAD

**Issue by Zapafaz** [jhelvy/splitKbCompare#92]
There is already a link to the awesome split kb repo so I thought adding a link to this site would also be a good idea since it has a lot (over 300 so far) of keyboards, many of which are split, and it's got nice filters to find them. https://mechdb.net/keyboards

**Comment by jhelvy** [comment]
I actually had a convo related to this site a while back. Forgot where, maybe a dm on reddit or discord. But the main idea was to link back to splikbcompare on each keyboard on mechdb.net that I have on my app. Something like a "compare?" button on mechdb that if you click it loads this app and has that board pre-selected. This is definitely do-able on this end. 

But even a simpler thing would just be to have a download button to download the layout as a PDF. Every board on this app has a hard link to a PDF of the layout, e.g. https://github.com/jhelvy/splitKbCompare/raw/master/images/pdf/letter/kyria.pdf

Anyway, yes this is a good idea to link to mechdb.net. Any suggestions where to put the link?

**Comment by Zapafaz** [comment]
Honestly I was just thinking of putting it in this repo's readme, but elsewhere on the site is a good idea too. Maybe at the bottom of the compare keyboard list, above the 'built with' link? Same on the 'keyboards' tab. That way if someone is looking for something and don't find it after scrolling they end up seeing the link - or links, if the awesome split kb repo is linked too.

**Comment by jhelvy** [comment]
Okay I just added it to the readme for now.
