### ISSUE TITLE
Update URL of this repo

### ISSUE THREAD

**Issue by fi0** [jhelvy/splitKbCompare#93]
The current URL shows https://jhelvy.github.io/splitKbCompare/. It should be updated to https://compare.splitkb.com .

**Comment by jhelvy** [comment]
Actually both urls are just pages that have embedded the true site hosting the app, which is https://jhelvy.shinyapps.io/splitkbcompare/. 

The https://compare.splitkb.com/ url is something Thomas put together to display the GitHub-hosted site on his site. If you view the source you'll see what it's doing: view-source:https://compare.splitkb.com/
