### ISSUE TITLE
Adding the ZSA Voyager

### ISSUE THREAD

**Issue by ezuk** [jhelvy/splitKbCompare#99]
Please complete this checklist and submit your issue - I will do my best to add your keyboard as soon as I can:

- [x] Keyboard name: ZSA Voyager
- [x] Url to vector graphic (e.g. svg, pdf, etc.) of switch plate: Attached as a file
[SplitKBCompare.zip](https://github.com/jhelvy/splitKbCompare/files/13602840/SplitKBCompare.zip)

- [x] Min and max number of keys: 56
- [x] Url to keyboard project source (if available): https://github.com/zsa/qmk_firmware/tree/firmware22/keyboards/voyager
- [x] Url to store to buy keyboard (if available): https://www.zsa.io/voyager

**Comment by jhelvy** [comment]
Hey! Just popping in to say that I did see this and it's on my map to do an update to add more boards, with the Voyager on the list. It's just finals week and a lot going on, so this is on the back burner for now. But I'd love to add the Voyager. My first split was an Ergodox EZ (still a really great and well-made board), and that was my gateway into the crazy world of boards. Really looking forward to trying out the Voyager as I've just started using a choc corne and I'm finding I really like the feel.

**Comment by ezuk** [comment]
Oh that's so nice to hear, @jhelvy ! Thank you, I appreciate the update and good luck to you and your students in the home stretch here. :)

**Comment by jhelvy** [comment]
It's finally [up](https://jhelvy.shinyapps.io/splitkbcompare/)! Sorry for the delay...now I gotta get my hands on a Voyager!

**Comment by ezuk** [comment]
Woo! Thank you! Can't wait to hear your thoughts on the board itself :)

**Comment by jhelvy** [comment]
My current daily driver is a corne, but I've always wanted the thumb key to be placed lower, and I only use the first two thumb keys (never use the most inner key). Looks like the voyager might be just the right compromise!

![Screen Shot 2024-04-01 at 11 24 14](https://github.com/jhelvy/splitKbCompare/assets/9012994/384ab47a-5414-4a8e-a7c6-c083a1b5f49a)

**Comment by jhelvy** [comment]
Finally got my hands on a Voyager, and I'll just say you've done a wonderful job with this board! I like the thumb key placement more than that of the Corne. Still need to play with the tenting options as I prefer a stronger tent, but I'll try to get the tripod mount to test that out. Overall, build quality is just so good, which is honestly one of the bigger issues with all the DIY boards. They tend to fall apart and need frequent repair, plus fiddling with QMK is annoying. Really smooth experience now with Oryx. Any future plans for an even smaller board? My ideal setup is a 34 key board - basically the Voyager without the outer columns or number row (I just ignore them for now...they don't take up too much space). Also, let me add that the two features I'm missing from QMK are 1) I can't seem to trigger caps WORD using a combo (I use a lot of combos for mods, etc), and 2) I don't see a way to do a one-shot combined mod, like Cmd+Shift. Both of those I've configured on QMK, so it must be possible. But in any case, just really lovely work here!

**Comment by ezuk** [comment]
Oh yay, that's so nice to hear! Thanks so much!

As for a smaller board: The zip kit covers do work with the Voyager, and you can also print your own if you have access to a 3d printer (https://www.printables.com/model/296223-zipf-kit) so the board can be made functionally smaller. :) 

As for caps-word with a combo and a one-shot combined mod, noted! We'll look into those. ❤️

**Comment by agriffis** [comment]
@ezuk Voyager is listed in this tool as having 56 keys, but I only count 52. Are there extra "keys" separate from the visible 24 grid and 2 thumb on each hand?

**Comment by jhelvy** [comment]
> @ezuk Voyager is listed in this tool as having 56 keys, but I only count 52. Are there extra "keys" separate from the visible 24 grid and 2 thumb on each hand?

Haha woops, looks like I can't count. You're totally correct - there are only 52 keys. The image is correct, I just need to update the data to show this. I'll fix it.

**Comment by gsauthof** [comment]
@jhelvy I'm curious, have you settled on some tenting option/setup with the Voyager, in the meantime?
And what tenting angle works best for you?
